name: Run API tests
on:
  schedule:
    - cron: '15 19 * * 1'
    - cron: '35 19 * * 1' 
  workflow_dispatch:
    inputs:
        environment:
          description: 'Environment'
          required: true
          default: 'staging' 
          type: choice
          options:
          - staging
          - development

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Set staging env
        if: ${{ inputs.environment == 'staging' || github.event.schedule == '15 19 * * 1'}}
        run: |
          echo "test_env=staging" >> $GITHUB_ENV    
      - name: Set dev env
        if: ${{ inputs.environment == 'development' || github.event.schedule == '35 19 * * 1'}}
        run: |
          echo "test_env=development" >> $GITHUB_ENV    
      - name: Run tests
        uses: ./
        run: WORK_ENV=${{ env.test_env }} node qq.js
